import type { Metadata } from 'next';
import './globals.css';
import { ColorProvider } from './context/ColorContext';
import QueryClientWrapper from './QueryClientWrapper';

export const metadata: Metadata = {
  title: 'Canon',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='min-h-full flex flex-col'>
        <QueryClientWrapper>
          <ColorProvider>{children}</ColorProvider>
        </QueryClientWrapper>
      </body>
    </html>
  );
}
